### ISSUE TITLE
No data returned by recorder / Newlines (0x0A) in .rec payload

### ISSUE THREAD

**Issue by RafhaanShah** [owntracks/recorder#374]
I'm trying to get the recorder set up using docker, here's my docker compose snippet:

```
 owntracks-recorder:
    container_name: owntracks-recorder
    image: owntracks/recorder:latest
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./data:/store
      - ./config:/config
    environment:
      - OTR_PORT=1883
      - OTR_HOST=192.168.1.3
      - OTR_HTTPHOST=0.0.0.0
      - OTR_HTTPHOST=localhost
      - OTR_HTTPPORT=8083
      - OTR_STORAGEDIR=/store
```

and my `recorder.conf` (auto generated, didn't change anything here):
```
OTR_TOPICS = "owntracks/#"
OTR_HTTPHOST = "0.0.0.0"
# OTR_CAPATH = "/config"
# OTR_CAFILE = "ca.pem"

# OTR_CERTFILE = "cert.pem"
# OTR_KEYFILE = "key.pem"
```

I've tried pushing data through both HTTP and MQTT, and they do show up when I look in the folders, such as `/store/rec/test2/phone2/2022-01.rec` -> `2022-01-08T21:32:04Z	*                 	{ 0A   "acc": 0, 0A   "lat": 51.517811, 0A   "lon": -0.184072, 0A   "tid": "t2", 0A   "tst": 1641660323, 0A   "topic": "owntracks/test2/phone2" 0A }`

But no data shows up on the web UI at all, the logs only had one error message saying `/store/last file or directory not found`, but nothing changed after I manually created the folder too. Any help would be appreciated.
