### ISSUE TITLE
HTTP Port is in use loop [DOCKER]

### ISSUE THREAD

**Issue by MayhemBill** [owntracks/recorder#387]
I've recently decided to setup my own OT server using docker, but I'm getting stuck on a loop of http port is in use. 
I am using the docker version
I have tried:
Changing the port in compose
changing the port via env variables
changing the port in the recorder.conf
verified nothing else is running on 8083

The container starts no problem, but it seems like otr can't start properly inside the container itself.

**Comment by jpmens** [comment]
That doesn’t sound right obviously.

Can you please show us how you’re starting the Recorder and which errors are displayed?

**Comment by MayhemBill** [comment]
I am using compose to run both the recorder and a mqtt server,

```
version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083

    volumes:
      - /home/mayhem/owntracks/config:/config
      - /home/mayhem/owntracks/store:/store
    restart: unless-stopped
    environment:
      - OTR_HTTPPORT=8083
      - OTR_HOST=192.168.1.128
      - OTR_PORT=1883

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - /home/mayhem/owntracks/mosquitto-data:/mosquitto/data
      - /home/mayhem/owntracks/mosquitto-logs:/mosquitto/logs
      - /home/mayhem/owntracks/mosquitto-conf:/mosquitto/config
    restart: unless-stopped
```
I have verified that r/w perms are available for all of the config and db files. and mosquitto has been configured and is running.

and this is what I get when starting the container.
```
ot-recorder[11]: version 0.8.8 starting with STORAGEDIR=/store
ot-recorder[11]: connecting to MQTT on 192.168.1.128:1883 as clientID ot-recorder-ccbbaaa417ca-11 without TLS
ot-recorder[11]: HTTP listener started on 
ot-recorder[11]: HTTP port is in use. Exiting.
```
