### ISSUE TITLE
conncetion refused when connecting with reverse proxy

### ISSUE THREAD

**Issue by sir-andreas** [owntracks/recorder#390]
Hi all, 
I run an instance of the recorder together with the mosquitto mqtt server. As it seems the connection between those seem to work.

When I am inside of to the recorder container I can also do a "curl 127.0.0.1:8083" and get  a proper result . 
But when I want to do this curl command from my nginx container I always get a "connection refused". A ping from there to the recorder container works by the way.  (the port is generally available, of course)

Is there anything left to setup?

Best regards,
Andreas

**Comment by jpmens** [comment]
Please show us how you have configured the recorder to start, its recorder.conf file and any other settings you may have specified.

**Comment by sir-andreas** [comment]
I did not change the recorcer.conf dile and here is my docker-compose:

```
version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    container_name: owntracks_recorder
    ports:
      - 8083:8083
    volumes:
      - ./data/recorder/store:/store
    restart: unless-stopped
    environment:
      - OTR_HOST=otmqtt
      - OTR_USER=andreas
      - OTR_PORT=1883
      - OTR_PASS=****

  otmqtt:
    image: eclipse-mosquitto
    container_name: owntracks_mqtt
    volumes:
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/logs:/mosquitto/logs
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/config/passwd:/etc/mosquitto/passwd
    restart: unless-stopped

networks:
  default:
    external:
      name: npm
```

**Comment by jpmens** [comment]
`OTR_HTTPHOST`, which you haven't configured, defaults to `localhost`, so the recorder is listening on `127.0.0.1` which is why you can talk to it from within the container. 

If you configure `OTR_HTTPHOST=0.0.0.0` in `environment` of your docker-compose file it will listen on all interfaces and should then do the right thing for you.

**Comment by sir-andreas** [comment]
I did this and restarted my containers. Also in docker ps i see the change since the container is now listening also to 0.0.0.0:8083 but I still get the message "connection refused"
is there anything else? Some authorization necessary?

**Comment by jpmens** [comment]
I have to ask: is there some firewall magic going on on this system?

If the recorder is running and listening on port 8083 then you ought to be able to connect to it via TCP which is what you would do with

```console
$ curl http://<containerIP>:8083/
```

**Comment by sir-andreas** [comment]
Just a small update on this case: When I am on the recorder container itself, a 

`curl localhost:8083`

and

`curl 127.0.0.1:8083 `

works quite well, while a 

`curl <container-IP>:8083 `

does not work. Strange ...

**Comment by jpmens** [comment]
If the recorder is listening on the loopback interface only, that means the configuration change (`OTR_HTTPHOST`) has not been applied.

**Comment by jpmens** [comment]
From your docker-compose file:

```
networks:
  default:
    external:
      name: npm
```

BTW, I do not know what this is/does and I note the name `npm` is not otherwise used in the YML, so might it be this is doing some magic we're not expecting?
