### ISSUE TITLE
open cage geocoding stop working 

### ISSUE THREAD

**Issue by centralhardware** [owntracks/recorder#453]
```
revgeo: REQUEST_DENIED ({
   "error_message" : "The provided API key is invalid. ",
   "results" : [],
   "status" : "REQUEST_DENIED"
})
```

**Comment by centralhardware** [comment]
I'm generate new api key, but it don't help

**Comment by jpmens** [comment]
Did you actually read the error message? How did you configure it?

**Comment by centralhardware** [comment]
geocoding stop working around UTC 14:00 today without any configuration change 
```
services:
  owntracks-recorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    environment:
      - OTR_PORT=0 # disables MQTT
      - OTR_LUASCRIPT=/send-to-bot.lua
      - OTR_GEOKEY="opencage:<api key>"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/alex/owntrack-recorder/send-to-bot.lua:/send-to-bot.lua
      - /home/alex/owntrack-recorder/config:/config
      - /home/alex/owntrack-recorder/store:/store
    restart: unless-stopped
```
