### ISSUE TITLE
Storage on mounted network drive

### ISSUE THREAD

**Issue by Th3H0ff** [owntracks/recorder#522]
Greetings
I have Owntracks recorder and frontend running as Docker containers on an Ubuntu server. This server has a drive mounted on my NAS which I wish to use for storing the recorder data. Owntracks works just fine when I use the local server drive as volume location for the recorder Docker container but if I point it to the NAS mount recorder starts but is unable to properly use the NAS mount. The folder ghash is created with two .mdb files in it but recorder doesn't process any MQTT packets and frontend cannot connect to backend. Docker log for backend is rather sparse, only + version 0.9.9 starting with STORAGEDIR=/store is written.

My Docker-compose is pretty basic. The #ed line is the one I use for the NAS drive.
```
version: '3'
services:

  owntrack-backend:
    image: owntracks/recorder
    container_name: owntrack-backend
    ports:
      - 8085:8085
    volumes:
      - /home/owntrack/config:/config
      - /home/owntrack/store:/store
        #- /media/owntracks:/store
    restart: unless-stopped
```

Is this something that should work, storing persistent recorder data on a network mount?
